### ISSUE TITLE
SPKL: Increase the timeout for unpack?

### ISSUE THREAD

**Issue by whobday** [scottdurow/SparkleXrm#401]
Is there a way to increase the timeout for the unpack command?  I have a particularly large solution that routinely times out.

**Comment by mariokrajmer** [comment]
+1

**Comment by AndersHybridPro** [comment]
Try to increase the MaxCrmConnectionTimeOutMinutes in the file: CrmSvcUtil.exe.config
If you have multiple versions of the Microsoft.CrmSdk.CoreTools in your packages folder, you need to find the correct one. I guess it will be the version in the current project where your spkl unpack bat-file resides.

**Comment by scottdurow** [comment]
This is definitely an issue that we need to find a fix for. It's actually something that the Power Platform Build Tools had until Microsoft updated them to use an async export - this API isn't publically available yet though.

**Comment by scottdurow** [comment]
I suspect there is something that we can do on the export using the Timeout values described here - https://ramontebar.net/2020/03/18/crmserviceclient-proxy-timeout/

**Comment by AndersHybridPro** [comment]
I have added CrmServiceClient.MaxConnectionTimeout = new TimeSpan(1, 0, 0); to the XrmToolingConnections Connect method, and that seems to have consistently worked.

**Comment by bermo** [comment]
I think I've experienced the same issue where `unpack.bat` seems to time out way too quickly. I also had a look at the code, and agree (in my case at least) it's related to **no** timeout increase (from the default 2 minutes) being set for the underlying `.Execute` calls. Note, I was previously connecting on-prem via legacy login with no issues (where it seems a timeout increase is being [set to an hour](https://github.com/scottdurow/SparkleXrm/blob/203181ae0d27e59390b0707807cc31a3003b732c/spkl/spkl/Program.cs#L169)).

I believe there are at least two workarounds for this timeout issue until a code change (like @AndersHybridPro is referring to) is merged in and a new package is released:
### 1.
The `CrmServiceClient.MaxConnectionTimeout` [doco](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.tooling.connector.crmserviceclient.maxconnectiontimeout?view=dynamics-xrmtooling-ce-9) says:

> _this property can also be set via app.config/app.settings with the property MaxCrmConnectionTimeOutMinutes_

Adding the following to` ~\..\packages\spkl.1.0.440\tools\spkl.exe.config` solved the problem:
```
<appSettings>
     <add key="MaxCrmConnectionTimeOutMinutes" value="20"/>
</appSettings>
```
### 2.
Provide a connection string using the `connection` property via command line, as it seems under this scenario, the [timeout value is already being set to an hour](https://github.com/scottdurow/SparkleXrm/blob/203181ae0d27e59390b0707807cc31a3003b732c/spkl/spkl/Program.cs#L198).

**Comment by scottdurow** [comment]
Fixed in https://www.nuget.org/packages/spkl/1.0.633-beta

**Comment by bondamak-tieto** [comment]
What if I still receive random timeout errors for `spkl` `1.0.640` `unpack.bat`?
```The application terminated with an error.
Message: The request channel timed out while waiting for a reply after 00:02:00. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.
Stack Trace:
Server stack trace:
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]:
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.Execute(OrganizationRequest request)
   at SparkleXrm.Tasks.SolutionPackagerTask.ExportUnmanagedSolution(SolutionPackageConfig config, String filePath)
   at SparkleXrm.Tasks.SolutionPackagerTask.UnPackSolution(SolutionPackageConfig solutionPackagerConfig, String targetFolder)
   at SparkleXrm.Tasks.SolutionPackagerTask.UnPack(OrganizationServiceContext ctx, ConfigFile config)
   at SparkleXrm.Tasks.SolutionPackagerTask.ExecuteInternal(String folder, OrganizationServiceContext ctx)
   at SparkleXrm.Tasks.BaseTask.Execute(String folder)
   at SparkleXrmTask.Program.RunTask(CommandLineArgs arguments, IOrganizationService service, ITrace trace)
   at SparkleXrmTask.Program.Run(CommandLineArgs arguments)
   at SparkleXrmTask.Program.Main(String[] args)
Inner Fault: The HTTP request to 'https://<org name>.crm4.dynamics.com/XRMServices/2011/Organization.svc/web?SDKClientVersion=9.0.44.892' has exceeded the allotted timeout of 00:02:00. The time allotted to this operation may have been a portion of a longer timeout.
Error Code=1
```

I checked `packages\spkl.1.0.640\tools\spkl.exe.config` and it contains
```
<appSettings>
  <add key="MaxCrmConnectionTimeOutMinutes" value="20" />
</appSettings>
```

UPD. The issue was that another developer installed older version (`1.0.440`) in another project in solution and `.bat` files were founding/using old `spkl.exe`
